name: test-env
on: workflow_dispatch
jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "GH_PAT len: ${#GH_PAT}"
          echo "GITHUB_TOKEN len: ${#GITHUB_TOKEN}"
        env:
          GH_PAT: ${{secrets.GH_PAT}}
